"""Use case package: one module per concern."""

from __future__ import annotations

from lens_application.use_cases._base import UseCase
from lens_application.use_cases._mapping import (
    category_to_dto,
    change_to_dto,
    channel_binding_to_dto,
    channel_to_dto,
    domain_to_dto,
    snapshot_to_dto,
    url_to_dto,
)
from lens_application.use_cases.api_keys import (
    CreateApiKeyUseCase,
    DeleteApiKeyUseCase,
    ListApiKeysUseCase,
)
from lens_application.use_cases.auto_learning import (
    ClusterTemplatesUseCase,
    EvalPipelineUseCase,
    LabelChangesUseCase,
    LearnZonesUseCase,
)
from lens_application.use_cases.categories import (
    CreateCategoryUseCase,
    DeleteCategoryUseCase,
    GetCategoryUseCase,
    ListCategoriesUseCase,
    UpdateCategoryUseCase,
)
from lens_application.use_cases.channels import (
    CreateChannelBindingUseCase,
    CreateChannelUseCase,
    DeleteChannelBindingUseCase,
    DeleteChannelUseCase,
    GetChannelBindingUseCase,
    GetChannelUseCase,
    ListChannelBindingsUseCase,
    ListChannelsUseCase,
    UpdateChannelBindingUseCase,
    UpdateChannelUseCase,
)
from lens_application.use_cases.crawl import (
    EnqueueDueUrlsUseCase,
    GetChangeDiffBlobUseCase,
    GetChangeDiffUseCase,
    GetChangeUseCase,
    GetLatestSnapshotUseCase,
    GetSnapshotUseCase,
    ListChangesUseCase,
    ListSnapshotsUseCase,
    ProcessCrawlTaskUseCase,
    TriggerCheckUseCase,
)
from lens_application.use_cases.domains import (
    CreateDomainUseCase,
    DeleteDomainUseCase,
    GetDomainUseCase,
    ListDomainsUseCase,
    UpdateDomainUseCase,
)
from lens_application.use_cases.enrich import EnrichChangeUseCase
from lens_application.use_cases.import_export import ExportSetupUseCase, ImportSetupUseCase
from lens_application.use_cases.notifications import (
    HandleChangeEventUseCase,
    HandleErrorEventUseCase,
    HandleStaleEventUseCase,
    PublishOutboxUseCase,
    SendTestNotificationUseCase,
)
from lens_application.use_cases.scaling import (
    DeleteSettingUseCase,
    DiscardDeadLetterUseCase,
    EnforceRetentionUseCase,
    GetSettingUseCase,
    InspectDeadLetterUseCase,
    ListSettingsUseCase,
    ReplayDeadLetterUseCase,
    SetSettingUseCase,
    SweepOrphanBlobsUseCase,
)
from lens_application.use_cases.urls import (
    CreateUrlUseCase,
    DeleteUrlUseCase,
    GetUrlUseCase,
    ListUrlsUseCase,
    UpdateUrlUseCase,
)

__all__ = [
    "ClusterTemplatesUseCase",
    "CreateApiKeyUseCase",
    "CreateCategoryUseCase",
    "CreateChannelBindingUseCase",
    "CreateChannelUseCase",
    "CreateDomainUseCase",
    "CreateUrlUseCase",
    "DeleteApiKeyUseCase",
    "DeleteCategoryUseCase",
    "DeleteChannelBindingUseCase",
    "DeleteChannelUseCase",
    "DeleteDomainUseCase",
    "DeleteSettingUseCase",
    "DeleteUrlUseCase",
    "DiscardDeadLetterUseCase",
    "EnforceRetentionUseCase",
    "EnqueueDueUrlsUseCase",
    "EnrichChangeUseCase",
    "EvalPipelineUseCase",
    "ExportSetupUseCase",
    "GetCategoryUseCase",
    "GetChangeDiffBlobUseCase",
    "GetChangeDiffUseCase",
    "GetChangeUseCase",
    "GetChannelBindingUseCase",
    "GetChannelUseCase",
    "GetDomainUseCase",
    "GetLatestSnapshotUseCase",
    "GetSettingUseCase",
    "GetSnapshotUseCase",
    "GetUrlUseCase",
    "HandleChangeEventUseCase",
    "HandleErrorEventUseCase",
    "HandleStaleEventUseCase",
    "ImportSetupUseCase",
    "InspectDeadLetterUseCase",
    "LabelChangesUseCase",
    "LearnZonesUseCase",
    "ListApiKeysUseCase",
    "ListCategoriesUseCase",
    "ListChangesUseCase",
    "ListChannelBindingsUseCase",
    "ListChannelsUseCase",
    "ListDomainsUseCase",
    "ListSettingsUseCase",
    "ListSnapshotsUseCase",
    "ListUrlsUseCase",
    "ProcessCrawlTaskUseCase",
    "PublishOutboxUseCase",
    "ReplayDeadLetterUseCase",
    "SendTestNotificationUseCase",
    "SetSettingUseCase",
    "SweepOrphanBlobsUseCase",
    "TriggerCheckUseCase",
    "UpdateCategoryUseCase",
    "UpdateChannelBindingUseCase",
    "UpdateChannelUseCase",
    "UpdateDomainUseCase",
    "UpdateUrlUseCase",
    "UseCase",
    "category_to_dto",
    "change_to_dto",
    "channel_binding_to_dto",
    "channel_to_dto",
    "domain_to_dto",
    "snapshot_to_dto",
    "url_to_dto",
]
