"""lens domain: pure business model (entities, value objects, services, events)."""

from __future__ import annotations

from lens_domain import entities, enums, errors, events, services, value_objects
from lens_domain.entities import (
    Category,
    Change,
    Channel,
    ChannelBinding,
    Domain,
    SiteProfile,
    Snapshot,
    Url,
)
from lens_domain.enums import (
    BindingScope,
    ChangeType,
    ChannelKind,
    EscalationReason,
    FetchMethod,
    LabelSource,
    SignificanceRuleType,
    TriggerType,
    UrlStatus,
)
from lens_domain.errors import (
    DomainError,
    DuplicateCategory,
    DuplicateDomain,
    DuplicateUrl,
    HostMismatch,
    InvalidAddress,
    InvalidHostname,
    InvalidInterval,
    InvalidPoliteness,
    InvalidScope,
    InvalidStateTransition,
    NoChannelsBound,
)
from lens_domain.events import (
    DriftRecommendationDetected,
)
from lens_domain.ids import CategoryId, ChangeId, DomainId, ProfileId, SnapshotId, UrlId
from lens_domain.services import (
    ChangeSignificanceEvaluator,
    EffectiveConfigResolver,
    GlobalDefaults,
)
from lens_domain.value_objects import (
    Address,
    ChangeClassification,
    ChangeLabel,
    ContentHash,
    CrawlConfig,
    DiffConfig,
    DiffSummary,
    EmbeddingSignal,
    Interval,
    NotificationRouting,
    Politeness,
    SignificanceRule,
    ZoneChangeObservation,
    ZoneSelector,
    ZoneTextDelta,
)

__version__ = "0.1.0"

__all__ = [
    "Address",
    "BindingScope",
    "Category",
    "CategoryId",
    "Change",
    "ChangeClassification",
    "ChangeId",
    "ChangeLabel",
    "ChangeSignificanceEvaluator",
    "ChangeType",
    "Channel",
    "ChannelBinding",
    "ContentHash",
    "CrawlConfig",
    "DiffConfig",
    "DiffSummary",
    "Domain",
    "DomainError",
    "DomainId",
    "DriftRecommendationDetected",
    "DuplicateCategory",
    "DuplicateDomain",
    "DuplicateUrl",
    "EffectiveConfigResolver",
    "EmbeddingSignal",
    "EscalationReason",
    "FetchMethod",
    "GlobalDefaults",
    "HostMismatch",
    "Interval",
    "InvalidAddress",
    "InvalidHostname",
    "InvalidInterval",
    "InvalidPoliteness",
    "InvalidScope",
    "InvalidStateTransition",
    "LabelSource",
    "NoChannelsBound",
    "NotificationRouting",
    "Politeness",
    "ProfileId",
    "SignificanceRule",
    "SignificanceRuleType",
    "SiteProfile",
    "Snapshot",
    "SnapshotId",
    "TriggerType",
    "Url",
    "UrlId",
    "UrlStatus",
    "ZoneChangeObservation",
    "ZoneSelector",
    "ZoneTextDelta",
    "entities",
    "enums",
    "errors",
    "events",
    "services",
    "value_objects",
]
